# 
# Home Assistant Automation Blueprint
#
# Synchronize on/off states on three devices
#
# Revision 1.1
# Modified by Johan Schelin, Mar. 2021
#

blueprint:
  name: Synchronize Three States
  description: Bind three entities together to act in unison (selected entites must all support the same state values)
  domain: automation
  input:
    switch_1:
      name: Entity 1
      selector:
        entity: {}
    switch_2:
      name: Entity 2
      selector:
        entity: {}
    switch_3:
      name: Entity 3
      selector:
        entity: {}
  source_url: https://github.com/johanschelin/ha_blueprints/blob/main/SyncStatesThree.yml
mode: restart
max_exceeded: silent
variables:
  switch_1: !input 'switch_1'
  switch_2: !input 'switch_2'
  switch_3: !input 'switch_3'
trigger:
- platform: state
  entity_id: !input 'switch_1'
- platform: state
  entity_id: !input 'switch_2'
- platform: state
  entity_id: !input 'switch_3'
action:
  - service: homeassistant.turn_{{ trigger.to_state.state }}
    data:
      entity_id: '{% if trigger.from_state.entity_id == switch_1 %} {{ switch_2 }} {% elif trigger.from_state.entity_id == switch_2 %} {{ switch_1 }} {% else %} {{ switch_1 }} {% endif %}'
  - service: homeassistant.turn_{{ trigger.to_state.state }}
    data:
      entity_id: '{% if trigger.from_state.entity_id == switch_1 %} {{ switch_3 }} {% elif trigger.from_state.entity_id == switch_2 %} {{ switch_3 }} {% else %} {{ switch_2 }} {% endif %}'